export const CART_GET_REQUEST = "CART_GET_REQUEST";
export const CART_SAVE_REQUEST = "CART_SAVE_REQUEST";
export const CART_GET_DONE = "CART_GET_DONE";

export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";

export const CART_UPDATE_ITEMS = "CART_UPDATE_ITEMS";
export const CART_UPDATE_ITEMS_DONE = "CART_UPDATE_ITEMS_DONE";

export const CART_GOTO_ITEMS = "CART_GOTO_ITEMS";
export const CART_GOTO_ACCOUNT_DETAILS = "CART_GOTO_ACCOUNT_DETAILS";
export const CART_GOTO_BILLING_DETAILS = "CART_GOTO_BILLING_DETAILS";
export const CART_GOTO_REVIEW_ORDER = "CART_GOTO_REVIEW_ORDER";

export const CART_UPDATE_STEP = "CART_UPDATE_STEP";
export const CART_UPDATE_STEP_DETAILS = "CART_UPDATE_STEP_DETAILS";

export const CART_PURCHASE_REQUEST = "CART_PURCHASE_REQUEST";
export const CART_PURCHASE_REQUEST_DONE = "CART_PURCHASE_REQUEST_DONE";

export const CART_PAY_INVOICE_REQUEST = "CART_PAY_INVOICE_REQUEST";
export const CART_PAY_INVOICE_REQUEST_DONE = "CART_PAY_INVOICE_REQUEST_DONE";


export const CART_UPDATE_INVOICE_DETAILS_REQUEST = "CART_UPDATE_INVOICE_DETAILS_REQUEST";
export const CART_UPDATE_INVOICE_DETAILS_DONE = "CART_UPDATE_INVOICE_DETAILS_DONE";

export const CART_CHECKS_EXISTING_EMAIL = "CART_CHECKS_EXISTING_EMAIL";

export const CART_CONFIRM_ACCOUNT_DETAILS = "CART_CONFIRM_ACCOUNT_DETAILS";
export const CART_CONFIRM_ACCOUNT_DETAILS_DONE =
  "CART_UPDATE_ACCOUNT_DETAILS_CHECKING_DONE";

export const CART_UPDATE_ACCOUNT_DETAILS_CHECKING = "CART_UPDATE_ACCOUNT_DETAILS_CHECKING";
export const CART_UPDATE_ACCOUNT_DETAILS_CHECKING_DONE =
  "CART_CONFIRM_ACCOUNT_DETAILS_DONE";

export const CART_CONFIRM_BILLING_DETAILS = "CART_CONFIRM_BILLING_DETAILS";
export const CART_CONFIRM_BILLING_DETAILS_DONE =
  "CART_CONFIRM_BILLING_DETAILS_DONE";

export const CART_SET_ADDONS = "CART_SET_ADDONS";

export const CART_APPLY_DISCOUNT = "CART_APPLY_DISCOUNT";
export const CART_APPLY_DISCOUNT_DONE = "CART_APPLY_DISCOUNT_DONE";

export const CART_STEPS = {
  accountDetails: 0,
  cartItems: 1,
  billingDetails: 2,
  reviewOrder: 3,
};

export const STEPS_CONFIG = [
  {
    title: "Account",
    icon: "user",
  },
  {
    title: "Product",
    icon: "shopping-cart",
  },
  {
    title: "Billing",
    icon: "wallet",
  },
  {
    title: "Review Order",
    icon: "file-done",
  },
];
