export const BILLINGS_FIND_REQUEST = "BILLINGS_FIND_REQUEST";
export const BILLINGS_FIND_DONE = "BILLINGS_FIND_DONE";

export const BILLINGS_TRANSACTION_FIND_REQUEST = "BILLINGS_TRANSACTION_FIND_REQUEST";
export const BILLINGS_TRANSACTION_FIND_DONE = "BILLINGS_TRANSACTION_FIND_DONE";

export const BILLINGS_INVOICES_FIND_REQUEST = "BILLINGS_INVOICES_FIND_REQUEST";
export const BILLINGS_INVOICES_FIND_DONE = "BILLINGS_INVOICES_FIND_DONE";

export const BILLINGS_GENERATE_PDF_REQUEST = "BILLINGS_GENERATE_PDF_REQUEST";
export const BILLINGS_GENERATE_PDF_DONE = "BILLINGS_GENERATE_PDF_DONE";
