export const PAYMENT_METHODS_GET_LIST = "PAYMENT_METHODS_GET_LIST";
export const PAYMENT_METHODS_GET_LIST_DONE = "PAYMENT_METHODS_GET_LIST_DONE";

export const PAYMENT_METHODS_CREATE_NEW = "PAYMENT_METHODS_CREATE_NEW";
export const PAYMENT_METHODS_CREATE_NEW_DONE = "PAYMENT_METHODS_CREATE_NEW_DONE";

export const PAYMENT_METHODS_DELETE_CARD = "PAYMENT_METHODS_DELETE_CARD";
export const PAYMENT_METHODS_DELETE_CARD_DONE = "PAYMENT_METHODS_DELETE_CARD_DONE";

export const PAYMENT_METHODS_SET_DEFAULT = "PAYMENT_METHODS_SET_DEFAULT";
export const PAYMENT_METHODS_SET_DEFAULT_DONE = "PAYMENT_METHODS_SET_DEFAULT_DONE";

export const PAYMENT_METHODS_PRODUCT_CREATE_NEW_CARD = "PAYMENT_METHODS_PRODUCT_CREATE_NEW_CARD";
export const PAYMENT_METHODS_PRODUCT_CREATE_NEW_CARD_DONE = "PAYMENT_METHODS_PRODUCT_CREATE_NEW_CARD_DONE";

export const PAYMENT_METHODS_PRODUCT_REPLACE_CARD = "PAYMENT_METHODS_PRODUCT_REPLACE_CARD";
export const PAYMENT_METHODS_PRODUCT_REPLACE_CARD_DONE = "PAYMENT_METHODS_PRODUCT_REPLACE_CARD_DONE";

export const PAYMENT_METHODS_PRODUCT_DELETE_CARD = "PAYMENT_METHODS_PRODUCT_DELETE_CARD";
export const PAYMENT_METHODS_PRODUCT_DELETE_CARD_DONE = "PAYMENT_METHODS_PRODUCT_DELETE_CARD_DONE";
