export const PROFILE_GET_USER_DETAILS = "PROFILE_GET_USER_DETAILS";
export const PROFILE_GET_USER_DETAILS_DONE = "PROFILE_GET_USER_DETAILS_DONE";

export const PROFILE_UPDATE_USER_DETAILS = "PROFILE_UPDATE_USER_DETAILS";
export const PROFILE_UPDATE_USER_DETAILS_DONE =
  "PROFILE_UPDATE_USER_DETAILS_DONE";

export const PROFILE_UPDATE_USER_IMAGE = "PROFILE_UPDATE_USER_IMAGE";
export const PROFILE_UPDATE_USER_IMAGE_DONE = "PROFILE_UPDATE_USER_IMAGE_DONE";

export const PROFILE_CHANGE_PASSWORD = "PROFILE_CHANGE_PASSWORD";
export const PROFILE_CHANGE_PASSWORD_DONE = "PROFILE_CHANGE_PASSWORD_DONE";

export const PROFILE_UPDATE_BACKUP_EMAIL = "PROFILE_UPDATE_BACKUP_EMAIL";
export const PROFILE_UPDATE_BACKUP_EMAIL_DONE =
  "PROFILE_UPDATE_BACKUP_EMAIL_DONE";

export const PROFILE_GET_OTHER_USER_DETAILS = "PROFILE_GET_OTHER_USER_DETAILS";
export const PROFILE_GET_OTHER_USER_DETAILS_DONE =
  "PROFILE_GET_OTHER_USER_DETAILS_DONE";
