export const CUSTOMER_PRODUCTS_GET_REQUEST = "CUSTOMER_PRODUCTS_GET_REQUEST";
export const CUSTOMER_PRODUCTS_GET_REQUEST_DONE = "CUSTOMER_PRODUCTS_GET_REQUEST_DONE";

export const CUSTOMER_PRODUCT_DETAIL_GET_REQUEST = "CUSTOMER_PRODUCT_DETAIL_GET_REQUEST";
export const CUSTOMER_PRODUCT_DETAIL_GET_REQUEST_DONE = "CUSTOMER_PRODUCT_DETAIL_GET_REQUEST_DONE";

export const CUSTOMER_TICKET_DETAIL_GET_REQUEST = "CUSTOMER_TICKET_DETAIL_GET_REQUEST";
export const CUSTOMER_TICKET_DETAIL_GET_REQUEST_DONE = "CUSTOMER_TICKET_DETAIL_GET_REQUEST_DONE";

export const CUSTOMER_PRODUCT_UPDATE_CUSTOM_VALUES_REQUEST = "CUSTOMER_PRODUCT_UPDATE_CUSTOM_VALUES_REQUEST";
export const CUSTOMER_PRODUCT_UPDATE_CUSTOM_VALUES_REQUEST_DONE = "CUSTOMER_PRODUCT_UPDATE_CUSTOM_VALUES_REQUEST_DONE";

export const CUSTOMER_PRODUCT_CHURN_MESSAGE_REQUEST = "CUSTOMER_PRODUCT_CHURN_MESSAGE_REQUEST";
export const CUSTOMER_PRODUCT_CHURN_MESSAGE_REQUEST_DONE = "CUSTOMER_PRODUCT_CHURN_MESSAGE_REQUEST_DONE";

export const CUSTOMER_PRODUCT_DEACTIVATE_SUBSCRIPTION_REQUEST = "CUSTOMER_PRODUCT_DEACTIVATE_SUBSCRIPTION_REQUEST";
export const CUSTOMER_PRODUCT_DEACTIVATE_SUBSCRIPTION_REQUEST_DONE = "CUSTOMER_PRODUCT_DEACTIVATE_SUBSCRIPTION_REQUEST_DONE";

export const CUSTOMER_PRODUCT_REACTIVATE_SUBSCRIPTION_REQUEST = "CUSTOMER_PRODUCT_REACTIVATE_SUBSCRIPTION_REQUEST";
export const CUSTOMER_PRODUCT_REACTIVATE_SUBSCRIPTION_REQUEST_DONE = "CUSTOMER_PRODUCT_REACTIVATE_SUBSCRIPTION_REQUEST_DONE";

export const CUSTOMER_PRODUCT_MODIFY_SUBSCRIPTION_REQUEST = "CUSTOMER_PRODUCT_MODIFY_SUBSCRIPTION_REQUEST";
export const CUSTOMER_PRODUCT_MODIFY_SUBSCRIPTION_REQUEST_DONE = "CUSTOMER_PRODUCT_MODIFY_SUBSCRIPTION_REQUEST_DONE";

export const PRODUCT_TYPES = {
  Event: "Event",
  Course: "Course", // thinkific
  Subscription: "Subscription",
  BundledCourses: "Bundled Courses", // thinkific
  BundledProducts: "Bundled Products",
  LiveStream: "Live Stream",
};

