export const SHOP_ADD_TO_CART = "SHOP_ADD_TO_CART";

export const SHOP_PRODUCTS_FIND_REQUEST = "SHOP_PRODUCTS_FIND_REQUEST";
export const SHOP_PRODUCTS_FIND_DONE = "SHOP_PRODUCTS_FIND_DONE";

export const SHOP_PRODUCTS_SET_FILTERED = "SHOP_PRODUCTS_SET_FILTERED";
