
export const CUSTOMERS_FIND_REQUEST = "CUSTOMERS_FIND_REQUEST";
export const CUSTOMERS_FIND_DONE = "CUSTOMERS_FIND_DONE";
export const CUSTOMER_SAVE_REQUEST = "CUSTOMER_SAVE_REQUEST";

export const CUSTOMER_INVOICES_FIND_REQUEST = "CUSTOMER_INVOICES_FIND_REQUEST";
export const CUSTOMER_INVOICES_FIND_DONE = "CUSTOMER_INVOICES_FIND_DONE";

export const CUSTOMER_TRANSACTIONS_FIND_REQUEST = "CUSTOMER_TRANSACTIONS_FIND_REQUEST";
export const CUSTOMER_TRANSACTIONS_FIND_DONE = "CUSTOMER_TRANSACTIONS_FIND_DONE";

export const CUSTOMER_PRODUCTS_FIND_REQUEST = "CUSTOMER_PRODUCTS_FIND_REQUEST";
export const CUSTOMER_PRODUCTS_FIND_DONE = "CUSTOMER_PRODUCTS_FIND_DONE";

export const CUSTOMER_BILLING_FIND_REQUEST = "CUSTOMER_BILLING_FIND_REQUEST";
export const CUSTOMER_BILLING_FIND_REQUEST_DONE = "CUSTOMER_BILLING_FIND_REQUEST_DONE";

export const CUSTOMER_BILLING_SET_LOADING = "CUSTOMER_BILLING_SET_LOADING";
